language: cpp

env:
  global:
    - LUAROCKS_BASE=luarocks-2.0.13

branches:
  only:
    - picojson-serializable

before_script:
  - sudo apt-get install libboost-dev
  - sudo apt-get install lua5.1 liblua5.1-dev

before_install:
  - lua$LUA_SFX -v
  # Install a recent luarocks release
  - wget http://luarocks.org/releases/$LUAROCKS_BASE.tar.gz
  - tar zxvpf $LUAROCKS_BASE.tar.gz
  - cd $LUAROCKS_BASE
  - ./configure
    --lua-version=5.1 --lua-suffix=5.1 --with-lua-include="/usr/include/lua5.1
  - sudo make
  - sudo make install
  - cd $TRAVIS_BUILD_DIR
  - luarocks install busted

script:
  - make -C Build config=release
  - cd simpletest
  - busted json_test.lua
  - cd ..
