language: cpp

before_script:
  - sudo apt-get install libboost-system-dev
  - sudo apt-get install lua5.1 liblua5.1-dev
  - sudo apt-get install luarocks
  - sudo luarocks install busted

script:
  - make -C Build/linux/gmake config=release64
  - ls -R bin
  - cd test
  - busted json_test.lua
  - cd ..
