language: cpp

before_script:
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install lua5.1 liblua5.1-dev
  - sudo apt-get install luarocks
  - sudo luarocks install busted

script:
  - make -C Build/linux/gmake config=release32
  - cd test
  - ls
  - busted json_test.lua
  - cd ..
